# Generated by Django 3.1.7 on 2021-03-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('accounts', '0002_auto_20210316_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='access',
            field=models.PositiveSmallIntegerField(choices=[(2, 'NORMAL'), (1, 'STORE ADMIN'), (0, 'SUPERUSER')], default=2),
        ),
        migrations.CreateModel(
            name='Store_Admin',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.useraccount')),
                ('Store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.useraccount',),
        ),
    ]
