# Generated by Django 3.1.7 on 2021-04-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210407_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='razorpay_orderID',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
