# Generated by Django 3.1.7 on 2021-03-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottletype',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('volume', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bottle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bottletype'),
        ),
    ]
